name: redin_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  audioplayers: ^6.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.14.3
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.10
  google_fonts: ^6.2.1
  http: ^1.3.0
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/redin_logo.png
    
    - assets/images/home/home_background.png
    - assets/images/home/welcomeCasino.png
    - assets/images/home/roulette.png
    - assets/images/home/blackjack.png
    - assets/images/home/luckyWheel.png
    - assets/images/home/slots.png
    - assets/images/home/horses.png

    - assets/images/roulette/ruleta.webp
    - assets/images/roulette/arrow.webp

    - assets/images/horse/rail.png
    - assets/images/horse/caballo_rojo.png
    - assets/images/horse/caballo_verde.png
    - assets/images/horse/caballo_azul.png
    - assets/images/horse/caballo_amarillo.png

    - assets/images/blackjack/table/card_thrower.webp
    - assets/images/blackjack/table/card_outline.webp
    - assets/images/blackjack/table/start_button.webp

    # Diamantes
    - assets/images/blackjack/cards/diamonds/2_of_diamonds.webp
    - assets/images/blackjack/cards/diamonds/3_of_diamonds.webp
    - assets/images/blackjack/cards/diamonds/4_of_diamonds.webp
    - assets/images/blackjack/cards/diamonds/5_of_diamonds.webp
    - assets/images/blackjack/cards/diamonds/6_of_diamonds.webp
    - assets/images/blackjack/cards/diamonds/7_of_diamonds.webp
    - assets/images/blackjack/cards/diamonds/8_of_diamonds.webp
    - assets/images/blackjack/cards/diamonds/9_of_diamonds.webp
    - assets/images/blackjack/cards/diamonds/10_of_diamonds.webp
    - assets/images/blackjack/cards/diamonds/jack_of_diamonds.webp
    - assets/images/blackjack/cards/diamonds/queen_of_diamonds.webp
    - assets/images/blackjack/cards/diamonds/king_of_diamonds.webp
    - assets/images/blackjack/cards/diamonds/ace_of_diamonds.webp

    # Corazones
    - assets/images/blackjack/cards/hearts/2_of_hearts.webp
    - assets/images/blackjack/cards/hearts/3_of_hearts.webp
    - assets/images/blackjack/cards/hearts/4_of_hearts.webp
    - assets/images/blackjack/cards/hearts/5_of_hearts.webp
    - assets/images/blackjack/cards/hearts/6_of_hearts.webp
    - assets/images/blackjack/cards/hearts/7_of_hearts.webp
    - assets/images/blackjack/cards/hearts/8_of_hearts.webp
    - assets/images/blackjack/cards/hearts/9_of_hearts.webp
    - assets/images/blackjack/cards/hearts/10_of_hearts.webp
    - assets/images/blackjack/cards/hearts/jack_of_hearts.webp
    - assets/images/blackjack/cards/hearts/queen_of_hearts.webp
    - assets/images/blackjack/cards/hearts/king_of_hearts.webp
    - assets/images/blackjack/cards/hearts/ace_of_hearts.webp

    # Tréboles
    - assets/images/blackjack/cards/clubs/2_of_clubs.webp
    - assets/images/blackjack/cards/clubs/3_of_clubs.webp
    - assets/images/blackjack/cards/clubs/4_of_clubs.webp
    - assets/images/blackjack/cards/clubs/5_of_clubs.webp
    - assets/images/blackjack/cards/clubs/6_of_clubs.webp
    - assets/images/blackjack/cards/clubs/7_of_clubs.webp
    - assets/images/blackjack/cards/clubs/8_of_clubs.webp
    - assets/images/blackjack/cards/clubs/9_of_clubs.webp
    - assets/images/blackjack/cards/clubs/10_of_clubs.webp
    - assets/images/blackjack/cards/clubs/jack_of_clubs.webp
    - assets/images/blackjack/cards/clubs/queen_of_clubs.webp
    - assets/images/blackjack/cards/clubs/king_of_clubs.webp
    - assets/images/blackjack/cards/clubs/ace_of_clubs.webp

    # Picas
    - assets/images/blackjack/cards/spades/2_of_spades.webp
    - assets/images/blackjack/cards/spades/3_of_spades.webp
    - assets/images/blackjack/cards/spades/4_of_spades.webp
    - assets/images/blackjack/cards/spades/5_of_spades.webp
    - assets/images/blackjack/cards/spades/6_of_spades.webp
    - assets/images/blackjack/cards/spades/7_of_spades.webp
    - assets/images/blackjack/cards/spades/8_of_spades.webp
    - assets/images/blackjack/cards/spades/9_of_spades.webp
    - assets/images/blackjack/cards/spades/10_of_spades.webp
    - assets/images/blackjack/cards/spades/jack_of_spades.webp
    - assets/images/blackjack/cards/spades/queen_of_spades.webp
    - assets/images/blackjack/cards/spades/king_of_spades.webp
    - assets/images/blackjack/cards/spades/ace_of_spades.webp

    - assets/images/blackjack/cards/Reverso.webp


    - assets/audio/casino.ogg
    - assets/audio/roulette/win.ogg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/redin_icon.webp"