name: redin_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  audioplayers: ^6.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/redin_logo.png
    - assets/images/home/home_background.png
    - assets/images/home/welcomeCasino.png
    - assets/images/home/roulette.png
    - assets/images/home/blackjack.png
    - assets/images/home/luckyWheel.png
    - assets/images/home/slots.png
    - assets/images/home/horses.png
    - assets/audio/casino.ogg
    - assets/audio/casino.mp3
    - assets/images/roulette/ruleta.webp
