name: redin_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  audioplayers: ^6.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.10
  google_fonts: ^6.2.1
  http: ^1.3.0
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/redin_logo.png
    - assets/images/home/home_background.png
    - assets/images/home/welcomeCasino.png
    - assets/images/home/roulette.png
    - assets/images/home/blackjack.png
    - assets/images/home/luckyWheel.png
    - assets/images/home/slots.png
    - assets/images/home/horses.png

    - assets/images/roulette/ruleta.webp
    - assets/images/roulette/arrow.webp

    - assets/images/horse/rail.png
    - assets/images/horse/caballo_rojo.png
    - assets/images/horse/caballo_verde.png
    - assets/images/horse/caballo_azul.png
    - assets/images/horse/caballo_amarillo.png

    - assets/images/blackjack/table/card_thrower.webp
    - assets/images/blackjack/table/card_outline.webp


    - assets/audio/casino.ogg
    - assets/audio/roulette/win.ogg


